apiVersion: v2
name: product-service
description: A Helm chart for Product Service microservice
type: application
version: 0.1.0 # Chart version
appVersion: "1.0.0" # Application version

keywords:
  - ecommerce
  - microservices
  - fastapi

maintainers:
  - name: DevOps Engineer
    email: devops@example.com
